/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Character = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'personality' : IDL.Text,
  'name' : IDL.Text,
  'creatorId' : IDL.Opt(IDL.Principal),
  'isOfficial' : IDL.Bool,
  'allowsRomance' : IDL.Bool,
  'avatarUrl' : IDL.Text,
  'gender' : IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'nonBinary' : IDL.Null,
  }),
  'fandom' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'timestamp' : IDL.Int,
  'characterId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacter' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'female' : IDL.Null,
          'male' : IDL.Null,
          'nonBinary' : IDL.Null,
        }),
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
  'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getUserCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileLegacy' : IDL.Func(
      [],
      [
        IDL.Record({
          'principal' : IDL.Principal,
          'characters' : IDL.Vec(Character),
        }),
      ],
      ['query'],
    ),
  'initializeApp' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'personality' : IDL.Text,
    'name' : IDL.Text,
    'creatorId' : IDL.Opt(IDL.Principal),
    'isOfficial' : IDL.Bool,
    'allowsRomance' : IDL.Bool,
    'avatarUrl' : IDL.Text,
    'gender' : IDL.Variant({
      'female' : IDL.Null,
      'male' : IDL.Null,
      'nonBinary' : IDL.Null,
    }),
    'fandom' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'timestamp' : IDL.Int,
    'characterId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacter' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'female' : IDL.Null,
            'male' : IDL.Null,
            'nonBinary' : IDL.Null,
          }),
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
    'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getUserCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileLegacy' : IDL.Func(
        [],
        [
          IDL.Record({
            'principal' : IDL.Principal,
            'characters' : IDL.Vec(Character),
          }),
        ],
        ['query'],
      ),
    'initializeApp' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
  });
};

export const init = ({ IDL }) => { return []; };