/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : bigint,
  'bio' : string,
  'personality' : string,
  'name' : string,
  'creatorId' : [] | [Principal],
  'isOfficial' : boolean,
  'allowsRomance' : boolean,
  'avatarUrl' : string,
  'gender' : { 'female' : null } |
    { 'male' : null } |
    { 'nonBinary' : null },
  'fandom' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'userId' : Principal,
  'role' : { 'user' : null } |
    { 'assistant' : null },
  'timestamp' : bigint,
  'characterId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      { 'female' : null } |
        { 'male' : null } |
        { 'nonBinary' : null },
      boolean,
      string,
    ],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[bigint], [] | [Character]>,
  'getCharacters' : ActorMethod<[], Array<Character>>,
  'getChatHistory' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getUserCharacters' : ActorMethod<[], Array<Character>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileLegacy' : ActorMethod<
    [],
    { 'principal' : Principal, 'characters' : Array<Character> }
  >,
  'initializeApp' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], ChatMessage>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];